fix linter

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -1,64 +1,64 @@
-# For most projects, this workflow file will not need changing; you simply need
-# to commit it to your repository.
+## For most projects, this workflow file will not need changing; you simply need
+## to commit it to your repository.
+##
+## You may wish to alter this file to override the set of languages analyzed,
+## or to provide custom queries or build logic.
+##
+## ******** NOTE ********
+## We have attempted to detect the languages in your repository. Please check
+## the `language` matrix defined below to confirm you have the correct set of
+## supported CodeQL languages.
+##
+#name: "CodeQL Advanced"
 #
-# You may wish to alter this file to override the set of languages analyzed,
-# or to provide custom queries or build logic.
+#on:
+#  push:
+#    branches: [ "main" ]
+#  pull_request:
+#    branches: [ "main" ]
+#  schedule:
+#    - cron: '17 17 * * 0'
+#  workflow_dispatch:
 #
-# ******** NOTE ********
-# We have attempted to detect the languages in your repository. Please check
-# the `language` matrix defined below to confirm you have the correct set of
-# supported CodeQL languages.
+#jobs:
+#  analyze:
+#    name: Analyze (${{ matrix.language }})
+#    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
+#    permissions:
+#      security-events: write
+#      packages: read
+#      actions: read
+#      contents: read
 #
-name: "CodeQL Advanced"
-
-on:
-  push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
-  schedule:
-    - cron: '17 17 * * 0'
-  workflow_dispatch:
-
-jobs:
-  analyze:
-    name: Analyze (${{ matrix.language }})
-    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
-    permissions:
-      security-events: write
-      packages: read
-      actions: read
-      contents: read
-
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-        - language: actions
-          build-mode: none
-        - language: python
-          build-mode: none
-    steps:
-    - name: Checkout repository
-      uses: actions/checkout@v4
-
-    - name: Initialize CodeQL
-      uses: github/codeql-action/init@v3
-      with:
-        languages: ${{ matrix.language }}
-        build-mode: ${{ matrix.build-mode }}
-
-    - if: matrix.build-mode == 'manual'
-      shell: bash
-      run: |
-        echo 'If you are using a "manual" build mode for one or more of the' \
-          'languages you are analyzing, replace this with the commands to build' \
-          'your code, for example:'
-        echo '  make bootstrap'
-        echo '  make release'
-        exit 1
-
-    - name: Perform CodeQL Analysis
-      uses: github/codeql-action/analyze@v3
-      with:
-        category: "/language:${{matrix.language}}"
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        include:
+#        - language: actions
+#          build-mode: none
+#        - language: python
+#          build-mode: none
+#    steps:
+#    - name: Checkout repository
+#      uses: actions/checkout@v4
+#
+#    - name: Initialize CodeQL
+#      uses: github/codeql-action/init@v3
+#      with:
+#        languages: ${{ matrix.language }}
+#        build-mode: ${{ matrix.build-mode }}
+#
+#    - if: matrix.build-mode == 'manual'
+#      shell: bash
+#      run: |
+#        echo 'If you are using a "manual" build mode for one or more of the' \
+#          'languages you are analyzing, replace this with the commands to build' \
+#          'your code, for example:'
+#        echo '  make bootstrap'
+#        echo '  make release'
+#        exit 1
+#
+#    - name: Perform CodeQL Analysis
+#      uses: github/codeql-action/analyze@v3
+#      with:
+#        category: "/language:${{matrix.language}}"
